
/EPol/construct/magFile polarimeter_magnet.dat.5GeV

#run macro for local testing
/vis/scene/add/axes 18.5446 0 -9280.5 100 cm
/vis/viewer/addCutawayPlane 0 0 0 m 0 -1 0

#detectors and components
/EPol/input/useBeam 1
/EPol/input/vertexPosX 18.5466 cm
/EPol/input/vertexPosY 0 cm
/EPol/input/vertexPosZ -9290.5 cm
#/EPol/input/vertexRotY 0.0103371112 rad

# Initialize kernel
/run/initialize
/run/beamOn 1

/vis/viewer/refresh
