
#run macro for local testing
/EPol/construct/magFile polarimeter_magnet.dat.5GeV
/EPol/input/name o_deleteMe.root

#detectors and components
/EPol/input/useBeam 1
/EPol/input/beamEnergy 5 GeV
/EPol/input/beamVx 18.5466 cm
/EPol/input/beamVy 0 cm
/EPol/input/beamVz -9290.5 cm
/EPol/input/beamPx 0.010336927
/EPol/input/beamPy 0
/EPol/input/beamPz 0.99994657


# Initialize kernel
/run/initialize
/run/beamOn 100

