
#run macro for local testing

#detectors and components


/EPol/construct/magFile polarimeter_magnet.dat.5GeV
/EPol/input/name /phenix/spin/phnxsp01/ciprian/eic/comptonOut/genIP6/e5GeV_g532nm_Pz98.ev

#/EPol/construct/magFile polarimeter_magnet.dat.10GeV
#/EPol/input/name /newVolatile/halla/moller12gev/ciprian/tmp/compton/e10GeV_g532nm_Pz91.ev

#/EPol/construct/magFile polarimeter_magnet.dat.18GeV
#/EPol/input/name /phenix/spin/phnxsp01/ciprian/eic/comptonOut/genIP6/e18GeV_g532nm_Pz71.cr

/EPol/input/vertexPosX 18.5466 cm
/EPol/input/vertexPosY 0 cm
/EPol/input/vertexPosZ -9290.5 cm
#/EPol/input/vertexRotY 0.0103371112 rad

# Initialize kernel
/run/initialize
/compton/output/name /phenix/spin/phnxsp01/ciprian/eic/comptonOut/genIP6/compton5GeV12digit_1e6.root
/run/beamOn 1000000

